AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 80
    
Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"
      
Metrics/BlockLength:    
  Exclude:
    - "config/environments/development"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
