AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 90
  Exclude:
    - "config/environments/**/*"
    - "Gemfile"
    - "config/initializers/content_security_policy.rb"   
    - "config/puma.rb"
    - "db/seeds.rb"
    - "db/migrate/**/*"
    - "config/initializers/filter_parameter_logging.rb"
    - "Rakefile"
    
Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"
    - "app/models/ability.rb"
      
Metrics/ClassLength:
  Exclude:
    - "test/models/**/*"
    - "test/controllers/**/*"
      
Metrics/BlockLength:    
  Exclude:
    - "config/**/*"
    - "test/controllers/**/*"
    - "test/factories/**/*"
    - "test/models/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "app/models/ability.rb"
