AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 90
  Exclude:
    - "config/environments/**/*"
    - "config/initializers/content_security_policy.rb"   
    - "config/initializers/filter_parameter_logging.rb"
    - "config/puma.rb"
    - "db/migrate/**/*"
    - "db/seeds.rb"
    - "Gemfile"
    - "Rakefile"
    
Metrics/AbcSize:
  Exclude:
    - "app/models/ability.rb"
    - "db/migrate/**/*"
      
Metrics/BlockLength:    
  Exclude:
    - "app/admin/**/*"
    - "app/models/**/associations.rb"
    - "config/**/*"
    - "test/controllers/**/*"
    - "test/factories/**/*"
    - "test/jobs/**/*"
    - "test/models/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/controllers/**/*"
    - "test/models/**/*"
      
Metrics/MethodLength:
  Exclude:
    - "app/models/ability.rb"
    - "db/migrate/*"
      
Style/FrozenStringLiteralComment:
  Exclude:
    - "templates/**/*"

Style/GlobalVars:
  Exclude:
    - "config/initializers/redis.rb"
